version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount the Firebase credentials
      - ./adminsdk.json:/app/adminsdk.json:ro
      - ./logs:/app/logs # Add this line to persist logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/adminsdk.json
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
